In [1]:
from jqdatasdk import *
import configparser
 
config = configparser.ConfigParser()
file = 'config.ini'
config.read(file)
user = config.get('login','user')
password = config.get('login','password')
auth(user,password)

auth success （JQData现有流量增加活动，详情请咨询JQData管理员，微信号：JQData02）

## 获取基金数据

我们目前包含多种ETF、LOF、分级A/B基金完整的行情、净值数据. 详情见[基金列表](https://www.joinquant.com/help/api/help?name=fund#%E5%9F%BA%E9%87%91%E5%88%97%E8%A1%A8)

更多API的可参考[官方API文档](https://www.joinquant.com/api)

### 基金概况：上市退市时间、代码、名称、累计/单位净值等

#### 获取单支基金数据

获取单支基金的信息.

**调用方法**

```
get_security_info(code)
```

**参数**

- code: 基金代码

**返回值**

\- 一个对象, 有如下属性:

- display_name # 中文名称
- name # 缩写简称
- start_date # 上市日期, [datetime.date] 类型
- end_date # 退市日期， [datetime.date] 类型, 如果没有退市则为2200-01-01
- type # 类型 etf(ETF基金)，fja（分级A），fjb（分级B）,fjm(分级母基金），lof(场内交易开发基金），mmf(场内交易货币基金）
- parent # 分级基金的母基金代码

**示例**

In [ ]:
get_security_info('159901.XSHE').start_date #获取深100ETF的上市日期

### 获取所有基金数据
获取平台支持的所有基金数据

**调用方法**

get_all_securities(['fund'])  
这里请在使用时注意防止未来函数。

**返回**
- display_name # 中文名称
- name # 缩写简称
- start_date # 上市日期
- end_date # 退市日期，如果没有退市则为2200-01-01
- type # 类型， etf(ETF基金)，fja（分级A），fjb（分级B）,fjm(分级母基金），lof(场内交易开发基金），mmf(场内交易货币基金） [pandas.DataFrame], 比如:get_all_securities(['fund'])[:2]返回:

In [7]:
get_all_securities(['fund'])[:2]

            display_name  name start_date   end_date type
150008.XSHE         瑞和小康  RHXK 2009-11-19 2200-01-01  fja
150009.XSHE         瑞和远见  RHYJ 2009-11-19 2200-01-01  fjb

In [9]:
# 获取所有etf , lof ,fja,fjb等类似
get_all_securities(['etf'])[:2]

            display_name  name start_date   end_date type
159001.XSHE          保证金   BZJ 2014-10-20 2200-01-01  etf
159003.XSHE         招商快线  ZSKX 2014-10-20 2200-01-01  etf

### 基金累计/单位净值
得到基金在一段时间的如下的数据:

acc_net_value: 基金累计净值  
unit_net_value: 基金单位净值

**调用方法**

get_extras(info, security_list, start_date='2015-01-01', end_date='2015-12-31', df=True,count=None):

**参数**

info: [‘acc_net_value’, ‘unit_net_value’] 中的一个  
security_list: 基金列表  
start_date/end_date: 开始结束日期, 同[get_price]  
df: 返回[pandas.DataFrame]对象还是一个dict, 同[history]  
count:限定返回条数

**返回值**

df=True:  
[pandas.DataFrame]对象, 列索引是基金代号, 行索引是[datetime.datetime], 比如get_extras('acc_net_value', ['510300.XSHG', '510050.XSHG'], start_date='2015-12-01', end_date='2015-12-03')返回:

In [10]:
get_extras('acc_net_value', ['510300.XSHG', '510050.XSHG'], start_date='2015-12-01', end_date='2015-12-03')

            510300.XSHG  510050.XSHG
2015-12-01       1.3950        3.119
2015-12-02       1.4432        3.251
2015-12-03       1.4535        3.254

df=False  
一个dict, key是基金代号, value是[numpy.ndarray], 比如 get_extras('acc_net_value', ['510300.XSHG', '510050.XSHG'], start_date='2015-12-01', end_date='2015-12-03', df=False) 返回:

In [11]:
get_extras('acc_net_value', ['510300.XSHG', '510050.XSHG'], start_date='2015-12-01', end_date='2015-12-03', df=False)

{'510050.XSHG': array([3.119, 3.251, 3.254]),
 '510300.XSHG': array([1.395 , 1.4432, 1.4535])}

### 场内基金份额数据
from jqdatasdk import *  
finance.run_query(query(finance.FUND_SHARE_DAILY).filter(finance.FUND_SHARE_DAILY.date=='2019-05-23').limit(n))

描述：记录每日场内基金份额数据

**参数：**

query(finance.FUND_SHARE_DAILY)：表示从finance.FUND_SHARE_DAILY这张表中查询每日场内基金份额数据，还可以指定所要查询的字段名，格式如下：query(库名.表名.字段名1，库名.表名.字段名2），多个字段用逗号分隔进行提取；query函数的更多用法详见：query简易教程

finance.FUND_SHARE_DAILY：收录了每日场内基金份额数据，表结构和字段信息如下：

**字段设计：**

 

| 名称          | 类型         | 描述                                                   |
| ------------- | ------------ | ------------------------------------------------------ |
| code          | varchar(12)  | 基金代码                                               |
| name          | varchar(50） | 基金简称                                               |
| exchange_code | varchar(12)  | 交易市场编码，XSHG-上海证券交易所；XSHE-深圳证券交易所 |
| date          | date         | 日期                                                   |
| shares        | bigint       | 基金份额（份）                                         |

filter(finance.FUND_SHARE_DAILY.date==date)：指定筛选条件，通过finance.FUND_SHARE_DAILY.date==date可以指定你想要查询的日期；除此之外，还可以对表中其他字段指定筛选条件；多个筛选条件用英文逗号分隔。

limit(n)：限制返回的数据条数，n指定返回条数。

**返回结果：**

返回一个 dataframe，每一行对应数据表中的一条数据， 列索引是您所查询的字段名称

**注意：**

1. 为了防止返回数据量过大, 我们每次最多返回3000行
2. 不能进行连表查询，即同时查询多张表的数据

**示例：**

In [12]:
#查询2019-05-23的场内基金份额数据。
df=finance.run_query(query(finance.FUND_SHARE_DAILY).filter(finance.FUND_SHARE_DAILY.date=='2019-05-23').limit(10))
df.head()

       id         code    name exchange_code        date    shares
0  960881  150008.XSHE    瑞和小康          XSHE  2019-05-23  17749200
1  960882  150009.XSHE    瑞和远见          XSHE  2019-05-23  17749200
2  960883  150012.XSHE  中证100A          XSHE  2019-05-23  36139500
3  960884  150013.XSHE  中证100B          XSHE  2019-05-23  54209300
4  960885  150016.XSHE     合润A          XSHE  2019-05-23  38111200

## 基金列表(点击省略号可以展开)
我们目前提供了近600种在交易所上市的基金的行情、净值等数据，包含ETF、LOF、分级AB以及货币基金。

(温馨提示：鉴于内容太多, 可使用Ctrl + F进行搜索)

In [17]:
import pandas as pd
# 设定最大显示行数、列数为10000
pd.set_option('display.max_rows', 10000)
pd.set_option('display.max_columns', 10000)
pd.set_option('display.width', 10000)


### ETF列表

In [18]:
get_all_securities('etf',date=None)

            display_name      name start_date   end_date type
159001.XSHE          保证金       BZJ 2014-10-20 2200-01-01  etf
159003.XSHE         招商快线      ZSKX 2014-10-20 2200-01-01  etf
159005.XSHE         添富快钱      TFKQ 2015-01-13 2200-01-01  etf
159901.XSHE      深100ETF   S100ETF 2006-04-24 2200-01-01  etf
159902.XSHE          中小板       ZXB 2006-09-05 2200-01-01  etf
159903.XSHE        深成ETF     SCETF 2010-02-02 2200-01-01  etf
159905.XSHE          深红利       SHL 2011-01-11 2200-01-01  etf
159906.XSHE          深成长       SCZ 2011-02-23 2200-01-01  etf
159907.XSHE        中小300     ZX300 2011-08-10 2200-01-01  etf
159908.XSHE         博时创业     SF200 2011-07-13 2200-01-01  etf
159909.XSHE         深TMT      STMT 2011-09-01 2200-01-01  etf
159910.XSHE        深F120     SF120 2011-09-27 2200-01-01  etf
159911.XSHE        民营ETF     MYETF 2011-10-14 2200-01-01  etf
159912.XSHE      深300ETF   S300ETF 2011-11-24 2200-01-01  etf
159913.XSHE          深价值       SJZ 2011-10-25 2200-01-01  etf
159915.XSHE          创业板       CYB 2011-12-09 2200-01-01  etf
159916.XSHE         深F60      SF60 2011-10-24 2200-01-01  etf
159918.XSHE        中创400     ZC400 2012-05-11 2200-01-01  etf
159919.XSHE       300ETF    300ETF 2012-05-28 2200-01-01  etf
159920.XSHE        恒生ETF     HSETF 2012-10-22 2200-01-01  etf
159921.XSHE         中小等权      ZXDQ 2013-01-31 2017-11-07  etf
159922.XSHE       500ETF    500ETF 2013-03-15 2200-01-01  etf
159923.XSHE       100ETF    100ETF 2013-03-05 2200-01-01  etf
159924.XSHE        300等权     300DQ 2013-06-05 2018-03-19  etf
159925.XSHE        南方300     NF300 2013-04-11 2200-01-01  etf
159926.XSHE        国债ETF     GZETF 2013-08-05 2200-01-01  etf
159927.XSHE      A300ETF   A300ETF 2013-08-16 2018-02-13  etf
159928.XSHE        消费ETF     XFETF 2013-09-16 2200-01-01  etf
159929.XSHE        医药ETF     YYETF 2013-09-16 2200-01-01  etf
159930.XSHE        能源ETF     NYETF 2013-09-16 2200-01-01  etf
159931.XSHE        金融ETF     JRETF 2013-09-16 2200-01-01  etf
159932.XSHE      500深ETF   500SETF 2013-10-21 2200-01-01  etf
159933.XSHE        金地ETF     JDETF 2013-10-16 2200-01-01  etf
159934.XSHE        黄金ETF     HJETF 2013-12-16 2200-01-01  etf
159935.XSHE        景顺500     JS500 2014-01-21 2200-01-01  etf
159936.XSHE         可选消费      KXXF 2014-06-25 2200-01-01  etf
159937.XSHE         博时黄金      BSHJ 2014-09-01 2200-01-01  etf
159938.XSHE         广发医药      GFYY 2015-01-08 2200-01-01  etf
159939.XSHE         信息技术      XXJS 2015-02-05 2200-01-01  etf
159940.XSHE         全指金融      QZJR 2015-04-17 2200-01-01  etf
159941.XSHE        纳指ETF     NZ100 2015-07-13 2200-01-01  etf
159942.XSHE        中创100     ZC100 2015-06-25 2018-11-05  etf
159943.XSHE        深证ETF     SZETF 2015-07-08 2200-01-01  etf
159944.XSHE         全指材料      QZCL 2015-07-06 2200-01-01  etf
159945.XSHE         全指能源      QZNY 2015-07-06 2200-01-01  etf
159946.XSHE         全指消费      QZXF 2015-07-13 2018-12-27  etf
159948.XSHE        创业板EF     CYBEF 2016-05-31 2200-01-01  etf
159949.XSHE        创业板50     CYB50 2016-07-22 2200-01-01  etf
159950.XSHE        深成指EF     SCZEF 2017-05-10 2019-07-11  etf
159951.XSHE         中关村A      ZGCA 2017-07-10 2200-01-01  etf
159952.XSHE        创业ETF     CYETF 2017-05-19 2200-01-01  etf
159953.XSHE        工业ETF     GYETF 2017-07-14 2200-01-01  etf
159954.XSHE        H股ETF     HGETF 2018-03-15 2200-01-01  etf
159955.XSHE         创业板E      CYBE 2017-08-23 2200-01-01  etf
159956.XSHE         创业板F      CYBF 2018-03-07 2200-01-01  etf
159957.XSHE        创业板HX     CYBHX 2018-01-04 2200-01-01  etf
159958.XSHE        创业板ET     CYBET 2018-01-19 2200-01-01  etf
159959.XSHE         银华央企      YHYQ 2019-01-18 2200-01-01  etf
159960.XSHE         恒生国企      HSGQ 2018-10-22 2200-01-01  etf
159961.XSHE         深100      S100 2018-12-19 2200-01-01  etf
159962.XSHE         四川国改      SCGG 2019-04-18 2200-01-01  etf
159963.XSHE         恒生中国      HSZG 2019-03-26 2200-01-01  etf
159964.XSHE        创业板PA     CYBPA 2019-04-19 2200-01-01  etf
159965.XSHE         央视50      YS50 2019-04-24 2200-01-01  etf
159966.XSHE          创蓝筹       CLC 2019-07-15 2200-01-01  etf
159967.XSHE          创成长       CCZ 2019-07-15 2200-01-01  etf
159971.XSHE        创业板FG     CYBFG 2019-07-02 2200-01-01  etf
161014.XSHE         富国汇利      FGHL 2017-12-18 2200-01-01  etf
161019.XSHE         富国天锋      FGTF 2012-06-28 2200-01-01  etf
161036.XSHE         娱乐增强      YLZQ 2017-03-24 2200-01-01  etf
161132.XSHE         易基科顺      YJKS 2019-01-28 2200-01-01  etf
161911.XSHE         万家强债      WJQZ 2013-08-01 2200-01-01  etf
163210.XSHE         诺安纯债      NACZ 2013-06-24 2200-01-01  etf
163417.XSHE         兴全合宜      XQHY 2018-04-23 2200-01-01  etf
164810.XSHE         工银纯债      GYCZ 2012-09-20 2200-01-01  etf
168401.XSHE         红土精选      HTDZ 2017-07-03 2200-01-01  etf
169106.XSHE         东证创优      DZCY 2018-06-20 2200-01-01  etf
501039.XSHG         添富睿丰      TFRF 2018-03-08 2200-01-01  etf
501049.XSHG         东证睿玺      DZRX 2018-06-01 2200-01-01  etf
501053.XSHG         东证目优      DZMY 2018-08-24 2200-01-01  etf
501054.XSHG         东证睿泽      DZRZ 2018-10-17 2200-01-01  etf
501063.XSHG         添富悦享      RFYX 2019-07-01 2200-01-01  etf
501064.XSHG         国泰价值      GTJZ 2019-05-16 2200-01-01  etf
501066.XSHG         东证恒元      DZHY 2019-04-26 2200-01-01  etf
510010.XSHG        治理ETF     ZLETF 2009-12-15 2200-01-01  etf
510020.XSHG        超大ETF     CDETF 2010-03-19 2200-01-01  etf
510030.XSHG        价值ETF     JZETF 2010-05-28 2200-01-01  etf
510050.XSHG        50ETF     50ETF 2005-02-23 2200-01-01  etf
510060.XSHG        央企ETF     YQETF 2009-10-27 2200-01-01  etf
510070.XSHG        民企ETF     MQETF 2010-10-29 2200-01-01  etf
510090.XSHG        责任ETF     ZRETF 2010-08-09 2200-01-01  etf
510110.XSHG        周期ETF     ZQETF 2010-11-15 2200-01-01  etf
510120.XSHG        非周ETF     FZETF 2011-06-08 2200-01-01  etf
510130.XSHG        中盘ETF     ZPETF 2010-06-23 2200-01-01  etf
510150.XSHG        消费ETF     XFETF 2011-02-25 2200-01-01  etf
510160.XSHG        小康ETF     XKETF 2010-11-01 2200-01-01  etf
510170.XSHG        商品ETF     SPETF 2011-01-25 2200-01-01  etf
510180.XSHG       180ETF    180ETF 2006-05-18 2200-01-01  etf
510190.XSHG        龙头ETF     LTETF 2011-01-10 2200-01-01  etf
510210.XSHG        综指ETF     ZZETF 2011-03-25 2200-01-01  etf
510220.XSHG        中小ETF     ZXETF 2011-03-28 2200-01-01  etf
510230.XSHG        金融ETF     JRETF 2011-05-23 2200-01-01  etf
510260.XSHG        新兴ETF     XXETF 2011-06-08 2200-01-01  etf
510270.XSHG        国企ETF     GQETF 2011-08-18 2200-01-01  etf
510280.XSHG        成长ETF     CZETF 2011-10-18 2200-01-01  etf
510290.XSHG       380ETF    380ETF 2011-11-08 2200-01-01  etf
510300.XSHG       300ETF    300ETF 2012-05-28 2200-01-01  etf
510310.XSHG     HS300ETF  HS300ETF 2013-03-25 2200-01-01  etf
510330.XSHG        华夏300     HX300 2013-01-16 2200-01-01  etf
510360.XSHG        广发300     GF300 2015-09-09 2200-01-01  etf
510380.XSHG        国寿300     GS300 2018-02-07 2200-01-01  etf
510390.XSHG        平安300     PA300 2018-01-26 2200-01-01  etf
510410.XSHG        资源ETF     ZYETF 2012-05-11 2200-01-01  etf
510420.XSHG     180EWETF  180EWETF 2012-07-09 2200-01-01  etf
510430.XSHG         50等权      50DQ 2012-09-24 2200-01-01  etf
510440.XSHG        500沪市     500HS 2012-10-08 2200-01-01  etf
510450.XSHG  上证180高贝塔ETF   180GETF 2013-08-01 2016-08-23  etf
510500.XSHG       500ETF    500ETF 2013-03-15 2200-01-01  etf
510510.XSHG        广发500     GF500 2013-05-24 2200-01-01  etf
510520.XSHG        诺安500     NA500 2014-03-10 2200-01-01  etf
510550.XSHG        方正500     FZ500 2019-01-16 2200-01-01  etf
510560.XSHG        国寿500     GS500 2015-07-03 2200-01-01  etf
510580.XSHG     ZZ500ETF  ZZ500ETF 2015-09-14 2200-01-01  etf
510590.XSHG        平安500     PA500 2018-05-04 2200-01-01  etf
510600.XSHG       沪50ETF    H50ETF 2018-09-20 2200-01-01  etf
510610.XSHG      华夏能源ETF      NYHY 2013-05-08 2016-07-05  etf
510620.XSHG      华夏材料ETF      CLHY 2013-05-08 2016-08-12  etf
510630.XSHG         消费行业      XFHY 2013-05-08 2200-01-01  etf
510650.XSHG         金融行业      JRHY 2013-05-08 2200-01-01  etf
510660.XSHG         医药行业      YYHY 2013-05-08 2200-01-01  etf
510680.XSHG         万家50      WJ50 2013-12-02 2200-01-01  etf
510700.XSHG  长盛上证市值百强ETF     BQETF 2013-05-31 2016-05-12  etf
510710.XSHG       上50ETF    S50ETF 2015-06-15 2200-01-01  etf
510800.XSHG         上证50      SZ50 2018-01-15 2200-01-01  etf
510810.XSHG         上海国企      SHGQ 2016-08-29 2200-01-01  etf
510820.XSHG         上海改革      SHGG 2019-07-09 2200-01-01  etf
510850.XSHG        工银上50     GYS50 2019-03-06 2200-01-01  etf
510880.XSHG        红利ETF     HLETF 2007-01-18 2200-01-01  etf
510890.XSHG         红利低波      HLDB 2019-06-24 2200-01-01  etf
510900.XSHG        H股ETF     HGETF 2012-10-22 2200-01-01  etf
511010.XSHG        国债ETF     GZETF 2013-03-25 2200-01-01  etf
511020.XSHG         活跃国债      HYGZ 2019-02-22 2200-01-01  etf
511030.XSHG          公司债       GSZ 2019-03-22 2200-01-01  etf
511210.XSHG        企债ETF     QZETF 2013-08-16 2018-01-25  etf
511220.XSHG        城投ETF     CTETF 2014-12-16 2200-01-01  etf
511230.XSHG          周期债       ZQZ 2017-04-21 2200-01-01  etf
511260.XSHG         十年国债      SNGZ 2017-08-24 2200-01-01  etf
511270.XSHG        10年地债     10NDZ 2018-11-22 2200-01-01  etf
511280.XSHG         中期信用      ZQXY 2018-05-31 2200-01-01  etf
511290.XSHG         国债十年      GZSN 2018-04-27 2200-01-01  etf
511310.XSHG          十年债       SNZ 2018-04-26 2200-01-01  etf
512000.XSHG        券商ETF     QSETF 2016-09-14 2200-01-01  etf
512010.XSHG        医药ETF     YYETF 2013-10-28 2200-01-01  etf
512040.XSHG         国信价值      GXJZ 2018-11-29 2200-01-01  etf
512070.XSHG        非银ETF     FYETF 2014-07-18 2200-01-01  etf
512090.XSHG       MSCI易基    MSCIYJ 2018-06-01 2200-01-01  etf
512100.XSHG      1000ETF   1000ETF 2016-11-04 2200-01-01  etf
512110.XSHG         中证地产      ZZDC 2014-01-06 2017-01-12  etf
512120.XSHG         医药50      ZZYY 2014-01-06 2200-01-01  etf
512150.XSHG       A50ETF    A50ETF 2019-01-21 2200-01-01  etf
512160.XSHG       MSCI基金    MSCIJJ 2018-04-27 2200-01-01  etf
512170.XSHG        医疗ETF     YLETF 2019-06-17 2200-01-01  etf
512180.XSHG       建信MSCI    JXMSCI 2018-05-21 2200-01-01  etf
512200.XSHG          房地产       FDC 2017-09-25 2200-01-01  etf
512210.XSHG         景顺食品      JSSP 2014-08-19 2018-08-30  etf
512220.XSHG        景顺TMT     JSTMT 2014-08-19 2200-01-01  etf
512230.XSHG         景顺医药      JSYY 2014-08-19 2019-01-22  etf
512260.XSHG        500低波     500DB 2019-01-11 2200-01-01  etf
512270.XSHG        300低波     300DB 2019-03-29 2200-01-01  etf
512280.XSHG       景顺MSCI    JSMSCI 2018-05-25 2200-01-01  etf
512290.XSHG         生物医药      SWYY 2019-05-20 2200-01-01  etf
512300.XSHG        500医药     500YY 2014-12-18 2200-01-01  etf
512310.XSHG        500工业     500GY 2015-05-08 2200-01-01  etf
512330.XSHG        500信息     500XX 2015-07-20 2200-01-01  etf
512340.XSHG        500原料     500YL 2015-05-15 2200-01-01  etf
512360.XSHG       MSCI国际    MSCIGJ 2018-07-20 2200-01-01  etf
512380.XSHG       银华MSCI    YHMSCI 2019-04-30 2200-01-01  etf
512390.XSHG       MSCI低波    MSCIDB 2018-07-13 2200-01-01  etf
512400.XSHG         有色金属      YSJS 2017-09-01 2200-01-01  etf
512480.XSHG          半导体       BDT 2019-06-12 2200-01-01  etf
512500.XSHG        中证500     ZZ500 2015-05-29 2200-01-01  etf
512510.XSHG       ETF500    ETF500 2015-06-12 2200-01-01  etf
512520.XSHG      MSCIETF   MSCIETF 2018-05-18 2200-01-01  etf
512550.XSHG        富时A50     FSA50 2017-08-07 2200-01-01  etf
512560.XSHG         中证军工      ZZJG 2017-07-28 2200-01-01  etf
512570.XSHG         中证证券      ZZZQ 2017-08-11 2200-01-01  etf
512580.XSHG        环保ETF     HBETF 2017-02-28 2200-01-01  etf
512590.XSHG          高股息       GGX 2019-03-08 2200-01-01  etf
512600.XSHG         主要消费      ZYXF 2014-07-25 2200-01-01  etf
512610.XSHG         医药卫生      YYWS 2014-07-25 2200-01-01  etf
512640.XSHG         金融地产      JRDC 2014-07-25 2200-01-01  etf
512660.XSHG        军工ETF     JGETF 2016-08-08 2200-01-01  etf
512680.XSHG         军工基金      JGJJ 2016-10-14 2200-01-01  etf
512690.XSHG         酒ETF      JETF 2019-05-06 2200-01-01  etf
512700.XSHG         银行基金      YHJJ 2017-07-26 2200-01-01  etf
512750.XSHG        基本面50     JBM50 2019-07-05 2200-01-01  etf
512760.XSHG        半导体50     BDT50 2019-06-12 2200-01-01  etf
512770.XSHG         战略新兴      ZLXX 2018-08-16 2200-01-01  etf
512780.XSHG         京津冀基      JJJJ 2018-05-24 2200-01-01  etf
512800.XSHG        银行ETF     YHETF 2017-08-03 2200-01-01  etf
512810.XSHG         军工行业      JGXY 2016-08-22 2200-01-01  etf
512820.XSHG         银行股基      YHGJ 2018-11-23 2200-01-01  etf
512850.XSHG         北京50      BJ50 2018-11-09 2200-01-01  etf
512860.XSHG       MSCI中国    MSCIZG 2018-10-26 2200-01-01  etf
512870.XSHG         杭州湾区      HZWQ 2019-02-22 2200-01-01  etf
512880.XSHG        证券ETF     ZQETF 2016-08-08 2200-01-01  etf
512890.XSHG         红利LV      HLLV 2019-01-18 2200-01-01  etf
512900.XSHG         证券基金      ZQJJ 2017-03-31 2200-01-01  etf
512910.XSHG       100ETF    100ETF 2019-07-01 2200-01-01  etf
512920.XSHG       MSCI新华    MSCIXH 2018-12-07 2200-01-01  etf
512950.XSHG         央企改革      YQGG 2019-01-18 2200-01-01  etf
512960.XSHG        央调ETF     YTETF 2019-01-18 2200-01-01  etf
512980.XSHG        传媒ETF     CMETF 2018-01-19 2200-01-01  etf
512990.XSHG       MSCIA股    MSCIAG 2015-03-25 2200-01-01  etf
513000.XSHG       225ETF    225ETF 2019-06-25 2200-01-01  etf
513030.XSHG         德国30      DG30 2014-09-05 2200-01-01  etf
513050.XSHG         中概互联      ZGHL 2017-01-18 2200-01-01  etf
513100.XSHG        纳指ETF     NZETF 2013-05-15 2200-01-01  etf
513500.XSHG        标普500     BP500 2014-01-15 2200-01-01  etf
513520.XSHG        日经ETF     RJETF 2019-06-25 2200-01-01  etf
513600.XSHG        恒指ETF     HZETF 2015-01-26 2200-01-01  etf
513660.XSHG          恒生通       HST 2015-01-26 2200-01-01  etf
513680.XSHG         建信H股      JXHG 2019-01-21 2200-01-01  etf
513800.XSHG        东证ETF     DZETF 2019-06-25 2200-01-01  etf
513880.XSHG        日经225     RJ225 2019-06-25 2200-01-01  etf
513900.XSHG        港股100     GG100 2018-05-25 2200-01-01  etf
518800.XSHG         黄金基金      GTHJ 2013-07-29 2200-01-01  etf
518880.XSHG        黄金ETF     HJETF 2013-07-29 2200-01-01  etf

### LOF列表

In [19]:
get_all_securities('lof',date=None)

              display_name    name start_date   end_date type
160105.XSHE           南方积配    NFJP 2004-12-20 2200-01-01  lof
160106.XSHE           南方高增    NFGZ 2005-09-21 2200-01-01  lof
160119.XSHE          南方500   NF500 2009-11-11 2200-01-01  lof
160123.XSHE       南方10年国债A   NF50Z 2011-07-25 2016-08-16  lof
160125.XSHE           南方香港    NFXG 2011-11-01 2200-01-01  lof
160128.XSHE           南方金利    NFJL 2012-07-16 2200-01-01  lof
160130.XSHE           南方永利    NFYL 2013-06-06 2200-01-01  lof
160131.XSHE           南方聚利    NFJL 2014-01-21 2200-01-01  lof
160133.XSHE           南方天元    NFTY 2014-08-25 2200-01-01  lof
160138.XSHE           国企精明    GQJM 2017-05-17 2019-04-22  lof
160140.XSHE         美国REIT  MGREIT 2017-11-24 2200-01-01  lof
160142.XSHE           南方配售    NFPS 2019-03-29 2200-01-01  lof
160211.XSHE           国泰小盘    GTXP 2010-01-07 2200-01-01  lof
160212.XSHE           国泰估值    GTGZ 2013-02-27 2200-01-01  lof
160215.XSHE           国泰价值    GTJZ 2010-09-13 2200-01-01  lof
160216.XSHE           国泰商品    GTSP 2015-04-07 2200-01-01  lof
160220.XSHE           国泰民益    GTMY 2014-01-16 2200-01-01  lof
160223.XSHE           创业板基    CYBJ 2016-11-28 2200-01-01  lof
160225.XSHE            新汽车     XQC 2016-07-20 2200-01-01  lof
160311.XSHE           华夏蓝筹    HXLC 2007-05-28 2200-01-01  lof
160314.XSHE           华夏行业    HXHY 2008-01-14 2200-01-01  lof
160322.XSHE           港股精选    GGJX 2017-07-24 2200-01-01  lof
160323.XSHE           华夏磐泰    HXPT 2017-03-15 2200-01-01  lof
160324.XSHE           华夏磐晟    HXPS 2017-08-08 2200-01-01  lof
160415.XSHE           华安量化  HAS300 2011-10-18 2200-01-01  lof
160416.XSHE           石油基金    SYJJ 2012-05-02 2200-01-01  lof
160421.XSHE           华安智增    HAZZ 2016-12-19 2200-01-01  lof
160422.XSHE   华安创业板50ETF联接    DZSJ 2017-05-26 2018-11-07  lof
160505.XSHE           博时主题    BSZT 2005-02-22 2200-01-01  lof
160512.XSHE           博时卓越    BSZY 2011-06-30 2200-01-01  lof
160513.XSHE           稳健债A    WJZA 2014-07-01 2200-01-01  lof
160515.XSHE           安丰18    AF18 2013-10-17 2200-01-01  lof
160518.XSHE           博时睿远     BSY 2016-07-11 2200-01-01  lof
160519.XSHE           博时睿利     BSL 2016-08-23 2200-01-01  lof
160520.XSHE            弘盈A     HYA 2016-10-26 2200-01-01  lof
160522.XSHE           博时睿益     BSY 2016-11-16 2200-01-01  lof
160607.XSHE           鹏华价值    PHJZ 2006-09-18 2200-01-01  lof
160610.XSHE           鹏华动力    PHDL 2007-03-09 2200-01-01  lof
160611.XSHE           鹏华治理    PHZL 2007-07-18 2200-01-01  lof
160613.XSHE           鹏华创新    PHCX 2008-11-10 2200-01-01  lof
160615.XSHE          鹏华300   PH300 2009-05-08 2200-01-01  lof
160616.XSHE          鹏华500   PH500 2010-04-28 2200-01-01  lof
160617.XSHE           鹏华丰润    PHFR 2010-12-16 2200-01-01  lof
160618.XSHE           鹏华丰泽    PHFZ 2014-12-25 2200-01-01  lof
160621.XSHE           鹏华丰和    PHFH 2013-01-09 2200-01-01  lof
160622.XSHE           鹏华丰利    PHFL 2016-05-24 2200-01-01  lof
160635.XSHE           医药基金    YYJJ 2016-08-01 2200-01-01  lof
160642.XSHE           鹏华增瑞    PHZR 2016-09-29 2200-01-01  lof
160643.XSHE           空天一体    KTYT 2017-06-20 2200-01-01  lof
160644.XSHE          互联网QD   HLWQD 2017-12-29 2200-01-01  lof
160706.XSHE          嘉实300   JS300 2005-10-17 2200-01-01  lof
160716.XSHE           嘉实50    JS50 2010-02-10 2200-01-01  lof
160717.XSHE           恒生H股    HSHG 2010-10-28 2200-01-01  lof
160719.XSHE           嘉实黄金    JSHJ 2012-02-10 2200-01-01  lof
160720.XSHE           中期企债    ZQQZ 2013-04-01 2200-01-01  lof
160722.XSHE           嘉实惠泽    JSHZ 2016-12-09 2200-01-01  lof
160723.XSHE           嘉实原油    JSYY 2017-05-05 2200-01-01  lof
160726.XSHE           嘉实瑞享    JSRX 2019-04-12 2200-01-01  lof
160805.XSHE           长盛同智    ZSTZ 2007-02-16 2200-01-01  lof
160806.XSHE           长盛同庆    ZSTQ 2015-08-06 2200-01-01  lof
160807.XSHE          长盛300   ZS300 2010-09-06 2200-01-01  lof
160809.XSHE           长盛同辉    CSTH 2017-12-05 2018-01-23  lof
160810.XSHE           长盛同丰    ZSTF 2014-07-11 2018-01-22  lof
160812.XSHE           长盛同益    ZSTY 2014-06-04 2200-01-01  lof
160813.XSHE           长盛同盛    ZSTS 2014-12-26 2200-01-01  lof
160910.XSHE           大成创新    DCCX 2007-10-25 2200-01-01  lof
160915.XSHE           大成景丰    DCJF 2013-12-02 2200-01-01  lof
160916.XSHE          优选LOF   YXLOF 2012-12-28 2200-01-01  lof
160918.XSHE           大成小盘    DCXP 2014-04-30 2200-01-01  lof
160919.XSHE           大成产业    DCCY 2015-01-09 2200-01-01  lof
160921.XSHE            多策略    DCDZ 2016-11-21 2200-01-01  lof
160922.XSHE           恒生中小    HSZX 2016-12-12 2200-01-01  lof
160924.XSHE          恒指LOF   HZLOF 2017-08-28 2200-01-01  lof
160925.XSHE          中华300   ZH300 2019-03-29 2200-01-01  lof
161005.XSHE           富国天惠    FGTH 2006-02-16 2200-01-01  lof
161010.XSHE           富国天丰    FGTF 2008-12-08 2200-01-01  lof
161015.XSHE           富国天盈    FGTY 2014-06-04 2200-01-01  lof
161017.XSHE          富国500   FG500 2011-10-21 2200-01-01  lof
161029.XSHE           银行FG    YHFG 2019-06-17 2200-01-01  lof
161033.XSHE           智能汽车    ZNQC 2016-02-29 2200-01-01  lof
161035.XSHE           医药增强    YYZQ 2016-11-25 2200-01-01  lof
161037.XSHE           高端制造    GDZZ 2017-05-11 2200-01-01  lof
161038.XSHE           成长量化    CZLH 2017-08-18 2200-01-01  lof
161039.XSHE         富国1000  FG1000 2018-06-20 2200-01-01  lof
161115.XSHE           易基岁丰    YJSF 2010-12-03 2200-01-01  lof
161116.XSHE           易基黄金    YJHJ 2011-11-08 2200-01-01  lof
161117.XSHE           易基永旭    YJYX 2012-07-18 2200-01-01  lof
161119.XSHE           易基综债    YJZZ 2013-01-09 2200-01-01  lof
161124.XSHE           香港小盘    XGXP 2016-11-10 2200-01-01  lof
161125.XSHE          标普500   BP500 2016-12-14 2200-01-01  lof
161126.XSHE           标普医药    BPYY 2016-12-14 2200-01-01  lof
161127.XSHE           标普生物    BPSW 2016-12-27 2200-01-01  lof
161128.XSHE           标普科技    BPKJ 2016-12-27 2200-01-01  lof
161129.XSHE           原油基金    YYJJ 2017-02-15 2200-01-01  lof
161130.XSHE          纳指LOF   NZLOF 2017-07-14 2200-01-01  lof
161131.XSHE           易基配售    YJPS 2019-03-29 2200-01-01  lof
161210.XSHE           国投新兴    GTXX 2010-07-01 2018-10-17  lof
161213.XSHE           国投消费    GTXF 2011-01-20 2200-01-01  lof
161216.XSHE            双债A     SZA 2011-05-20 2200-01-01  lof
161217.XSHE           国投资源    GTZY 2011-08-29 2200-01-01  lof
161219.XSHE           国投产业    GTCY 2012-01-16 2200-01-01  lof
161222.XSHE           国投瑞利    GTRL 2015-05-04 2200-01-01  lof
161224.XSHE           国投丝路    GTSL 2015-05-06 2200-01-01  lof
161225.XSHE           国投瑞盈    GTRY 2015-08-14 2200-01-01  lof
161226.XSHE           白银基金    BYJJ 2015-08-17 2200-01-01  lof
161227.XSHE          深证100   SZ100 2015-08-28 2200-01-01  lof
161229.XSHE           国投中国    GTZG 2016-01-04 2200-01-01  lof
161230.XSHE           丰利A类    FLAL 2016-02-25 2018-09-17  lof
161232.XSHE           国投瑞盛    GTRS 2016-08-19 2200-01-01  lof
161233.XSHE           国投瑞泰    GTRS 2017-02-27 2200-01-01  lof
161505.XSHE           银河通利    YHTL 2014-05-23 2200-01-01  lof
161607.XSHE           融通巨潮    RTJC 2005-06-16 2200-01-01  lof
161610.XSHE           融通领先    RTLX 2007-07-18 2200-01-01  lof
161614.XSHE           融通添利    RTTL 2012-04-06 2200-01-01  lof
161626.XSHE           融通通福    RTTF 2017-01-10 2200-01-01  lof
161630.XSHE           融通农业    RTNY 2017-02-15 2018-01-05  lof
161631.XSHE           人工智能    RGZN 2017-04-19 2200-01-01  lof
161706.XSHE           招商成长    ZSCZ 2005-12-09 2200-01-01  lof
161713.XSHE           招商信用    ZSXY 2010-07-30 2200-01-01  lof
161714.XSHE           招商金砖    ZSJZ 2011-05-11 2200-01-01  lof
161715.XSHE           大宗商品    DZSP 2017-07-14 2200-01-01  lof
161716.XSHE           招商双债    ZSSZ 2015-03-16 2200-01-01  lof
161722.XSHE           招商丰泰    ZSFT 2015-07-22 2200-01-01  lof
161727.XSHE           招商增荣    ZSZR 2016-07-07 2200-01-01  lof
161728.XSHE           招商配售    ZSPS 2019-03-29 2200-01-01  lof
161810.XSHE           银华内需    YHNX 2009-10-16 2200-01-01  lof
161813.XSHE           银华信用    YHXY 2010-07-09 2019-01-02  lof
161815.XSHE           银华通胀    YHTZ 2010-12-20 2200-01-01  lof
161820.XSHE           银华纯债    YHCZ 2012-09-05 2200-01-01  lof
161821.XSHE          银华50A   YH50A 2013-01-18 2017-07-17  lof
161823.XSHE           银华永兴    YHYX 2016-02-17 2200-01-01  lof
161831.XSHE           恒生中企    HGFJ 2015-04-13 2200-01-01  lof
161834.XSHE           银华鑫锐     YHR 2016-09-23 2200-01-01  lof
161835.XSHE           银华惠丰    YHHF 2017-06-19 2200-01-01  lof
161903.XSHE           万家优选    WJYX 2005-08-15 2200-01-01  lof
161907.XSHE           万家红利    WJHL 2011-06-15 2200-01-01  lof
161908.XSHE           万家添利    WJTL 2014-06-16 2200-01-01  lof
161912.XSHE           社会责任    SHZR 2019-06-14 2200-01-01  lof
162006.XSHE           长城久富    CCJF 2007-05-18 2200-01-01  lof
162105.XSHE           持久增利    CJZL 2015-03-20 2200-01-01  lof
162108.XSHE           元盛债券    YSZQ 2015-05-20 2200-01-01  lof
162207.XSHE           泰达效率    TDXL 2006-07-21 2200-01-01  lof
162215.XSHE           泰达聚利    SDJL 2016-05-25 2200-01-01  lof
162307.XSHE          海富100   HF100 2010-01-08 2200-01-01  lof
162308.XSHE           海富增利    HFZL 2014-09-16 2017-04-27  lof
162411.XSHE           华宝油气    HBYQ 2012-06-08 2200-01-01  lof
162414.XSHE            新机遇     XJY 2015-07-01 2200-01-01  lof
162415.XSHE           美国消费    MGXF 2016-04-06 2200-01-01  lof
162416.XSHE           香港本地    XGBD 2018-04-18 2200-01-01  lof
162510.XSHE           国安双力    GASL 2015-05-20 2200-01-01  lof
162605.XSHE           景顺鼎益    JSDY 2005-05-25 2200-01-01  lof
162607.XSHE           景顺资源    JSZY 2006-04-07 2200-01-01  lof
162703.XSHE           广发小盘    GFXP 2005-04-29 2200-01-01  lof
162711.XSHE         广发500L  GF500L 2010-01-08 2200-01-01  lof
162712.XSHE           广发聚利    GFJL 2011-10-27 2200-01-01  lof
162715.XSHE           广发聚源    GFJY 2013-07-10 2200-01-01  lof
162717.XSHE            再融资     GFJ 2016-12-29 2200-01-01  lof
162718.XSHE           广发鑫瑞    GFXR 2017-03-24 2200-01-01  lof
162719.XSHE           广发石油    GFSY 2017-03-17 2200-01-01  lof
163001.XSHE           长信医疗    ZXYL 2010-04-16 2200-01-01  lof
163003.XSHE           长信利鑫     CXL 2016-07-22 2200-01-01  lof
163005.XSHE           长信利众    ZXLZ 2016-03-16 2200-01-01  lof
163110.XSHE           申万量化    SWLH 2011-08-01 2200-01-01  lof
163111.XSHE           申万中小    SWZX 2017-05-26 2200-01-01  lof
163119.XSHE           申万健康    SWJK 2016-11-01 2200-01-01  lof
163208.XSHE           诺安油气    NAYQ 2015-02-17 2200-01-01  lof
163302.XSHE           大摩资源    DMZY 2007-07-05 2200-01-01  lof
163402.XSHE           兴全趋势    XQQS 2006-01-19 2200-01-01  lof
163407.XSHE          兴全300   XQ300 2011-01-19 2200-01-01  lof
163409.XSHE           兴全绿色    XQLS 2011-07-07 2200-01-01  lof
163412.XSHE           兴全轻资    XQQZ 2012-05-31 2200-01-01  lof
163415.XSHE           兴全模式    XQMS 2013-02-01 2200-01-01  lof
163503.XSHE           天治核心    TZHX 2007-07-30 2200-01-01  lof
163801.XSHE           中银中国    ZYZG 2005-02-23 2200-01-01  lof
163819.XSHE           中银信用    ZYXY 2012-07-18 2200-01-01  lof
163821.XSHE         中银300E  ZY300E 2012-07-13 2200-01-01  lof
163824.XSHE           中银盛利    ZYSL 2013-11-04 2200-01-01  lof
163827.XSHE           中银产债    ZYCZ 2014-12-18 2200-01-01  lof
163907.XSHE           中海惠裕    ZHHY 2016-03-03 2200-01-01  lof
164105.XSHE           华富强债    HFQZ 2010-10-11 2200-01-01  lof
164206.XSHE           天弘添利    THTL 2015-12-15 2200-01-01  lof
164208.XSHE           天弘丰利    THFL 2014-12-03 2200-01-01  lof
164210.XSHE           天弘同利    THTL 2016-09-30 2200-01-01  lof
164302.XSHE           新华惠鑫    XHHX 2017-02-24 2019-01-15  lof
164403.XSHE           农业精选    NYJX 2016-08-15 2200-01-01  lof
164509.XSHE           国富恒利    GFHL 2017-04-07 2200-01-01  lof
164606.XSHE           信用增利    XYZL 2011-12-12 2200-01-01  lof
164701.XSHE           添富贵金    TFGJ 2012-03-01 2200-01-01  lof
164702.XSHE           添富季红    TFJH 2012-10-25 2200-01-01  lof
164703.XSHE           添富纯债    TFCZ 2016-12-02 2200-01-01  lof
164705.XSHE           添富恒生    TFHS 2015-04-13 2200-01-01  lof
164808.XSHE           工银四季    GYSJ 2011-03-28 2200-01-01  lof
164812.XSHE           政府债基    GYZL 2016-03-29 2018-06-27  lof
164814.XSHE           工银双债    GYSZ 2013-12-23 2200-01-01  lof
164815.XSHE          原油LOF    GYZY 2013-06-18 2017-06-19  lof
164823.XSHE          深成LOF   SCLOF 2017-10-13 2018-05-10  lof
164824.XSHE           印度基金    YDJJ 2018-08-01 2200-01-01  lof
164902.XSHE           交银添利    JYTL 2011-04-20 2200-01-01  lof
164906.XSHE           中国互联    ZGHL 2015-07-10 2200-01-01  lof
165309.XSHE          建信300   JX300 2009-11-30 2200-01-01  lof
165311.XSHE           建信信用    JXXY 2011-09-09 2200-01-01  lof
165313.XSHE           建信优势    JXYS 2013-04-03 2200-01-01  lof
165317.XSHE           建信丰裕    JXFY 2017-10-13 2200-01-01  lof
165508.XSHE           信诚深度    XCSD 2010-09-20 2200-01-01  lof
165509.XSHE           信诚增强    XCZQ 2010-11-08 2200-01-01  lof
165510.XSHE           信诚四国    XCSG 2011-01-20 2200-01-01  lof
165512.XSHE           信诚机遇    XCJY 2011-09-16 2200-01-01  lof
165513.XSHE           信诚商品    XCSP 2012-01-13 2200-01-01  lof
165516.XSHE           信诚周期    XCZQ 2012-11-05 2200-01-01  lof
165517.XSHE           信诚双盈    XCSY 2015-04-23 2200-01-01  lof
165525.XSHE           基建工程    JJGC 2016-12-09 2200-01-01  lof
165528.XSHE           信诚鼎利    XCDZ 2016-08-31 2200-01-01  lof
165705.XSHE           诺德双翼    NDSY 2015-03-20 2018-07-25  lof
165806.XSHE          东吴100   DW100 2012-04-27 2018-07-10  lof
165807.XSHE           东吴鼎利    DWDL 2016-05-20 2200-01-01  lof
166001.XSHE           中欧趋势    ZOQS 2007-04-23 2200-01-01  lof
166006.XSHE           中欧成长    ZOCZ 2010-03-26 2200-01-01  lof
166007.XSHE      中欧互通精选混合A   ZO300 2010-08-16 2018-09-28  lof
166008.XSHE           中欧强债    ZOQZ 2011-02-18 2200-01-01  lof
166009.XSHE           中欧动力    ZODL 2011-04-29 2200-01-01  lof
166011.XSHE           中欧盛世    ZOSS 2015-04-21 2200-01-01  lof
166012.XSHE           中欧信用    ZOXY 2016-01-08 2200-01-01  lof
166016.XSHE           中欧纯债    ZOCZ 2016-03-01 2200-01-01  lof
166023.XSHE           中欧瑞丰    ZORF 2017-09-15 2200-01-01  lof
166024.XSHE           中欧恒利    ZOHL 2017-12-06 2200-01-01  lof
166025.XSHE           中欧远见    ZOYJ 2019-05-27 2200-01-01  lof
166105.XSHE           信达鑫安    XDZL 2015-06-04 2200-01-01  lof
166401.XSHE            增利C    PYZL 2015-01-08 2200-01-01  lof
166402.XSHE           沪港深F    HGSF 2017-06-09 2200-01-01  lof
166902.XSHE           民生增利    MSZL 2013-01-30 2200-01-01  lof
166904.XSHE           民生添利    MSTL 2013-10-29 2200-01-01  lof
167001.XSHE           平安鼎泰    PADS 2016-10-18 2200-01-01  lof
167002.XSHE           平安鼎越    PADY 2016-12-19 2200-01-01  lof
167003.XSHE           平安鼎弘    PADH 2017-06-06 2200-01-01  lof
167501.XSHE           安信宝利    AXBL 2015-08-07 2200-01-01  lof
167901.XSHE          华宸300   HC300 2013-06-03 2016-05-05  lof
168002.XSHE           国寿精选    GSJX 2017-10-23 2200-01-01  lof
168101.XSHE           九泰锐智    JSRZ 2015-09-15 2200-01-01  lof
168102.XSHE           九泰锐富    JSRF 2016-05-04 2200-01-01  lof
168103.XSHE           九泰锐益    JSRY 2016-11-23 2200-01-01  lof
168104.XSHE           九泰锐丰    JSRF 2016-12-15 2200-01-01  lof
168105.XSHE           九泰泰富    JSSF 2017-01-10 2200-01-01  lof
168106.XSHE            盈华A    JSRH 2017-06-16 2200-01-01  lof
168108.XSHE           九泰锐诚    JSRC 2017-07-11 2200-01-01  lof
168301.XSHE           东海祥龙    DHXL 2017-02-27 2200-01-01  lof
169101.XSHE           东证睿丰     DZF 2015-03-06 2200-01-01  lof
169102.XSHE           东证睿阳     DZY 2015-07-31 2200-01-01  lof
169103.XSHE           东证睿轩     DZX 2016-08-15 2200-01-01  lof
169104.XSHE           东证睿满    DZRM 2017-02-21 2200-01-01  lof
169105.XSHE           东证睿华    DZRH 2017-02-21 2200-01-01  lof
169201.XSHE           浙商鼎盈    ZSDY 2017-03-16 2200-01-01  lof
184801.XSHE           鹏华前海    PHQH 2015-09-30 2200-01-01  lof
501000.XSHG  国金鑫新灵活配置(LOF)    GJXX 2015-07-14 2200-01-01  lof
501001.XSHG           财通精选    CTJX 2015-09-25 2200-01-01  lof
501002.XSHG           能源互联    NYHL 2016-02-01 2019-02-28  lof
501003.XSHG           长信优选    SHGG 2017-05-05 2018-10-25  lof
501005.XSHG           精准医疗    JZYL 2016-03-21 2200-01-01  lof
501006.XSHG           精准医C    JZYC 2016-03-21 2200-01-01  lof
501007.XSHG           互联医疗    HLYL 2017-02-20 2200-01-01  lof
501008.XSHG           互联医C    HLYC 2017-02-20 2200-01-01  lof
501009.XSHG           生物科技    SWKJ 2017-02-20 2200-01-01  lof
501010.XSHG           生物科C    SWKC 2017-02-20 2200-01-01  lof
501011.XSHG           中药基金    ZYJJ 2017-02-20 2200-01-01  lof
501012.XSHG            中药C     ZYC 2017-02-20 2200-01-01  lof
501015.XSHG           财通升级    CTSJ 2016-06-06 2200-01-01  lof
501016.XSHG           券商基金    QSJJ 2017-05-19 2200-01-01  lof
501017.XSHG           国泰融丰    GSRF 2016-08-26 2200-01-01  lof
501018.XSHG           南方原油    NFYY 2016-06-28 2200-01-01  lof
501019.XSHG           军工基金    JGJJ 2017-04-21 2200-01-01  lof
501020.XSHG            国企改     GQG 2017-04-21 2018-11-13  lof
501021.XSHG           香港中小    XGZX 2016-07-06 2200-01-01  lof
501022.XSHG           银华鑫盛     YHS 2016-11-10 2200-01-01  lof
501023.XSHG           港中小企    GZXQ 2016-10-24 2200-01-01  lof
501025.XSHG           香港银行    XGYX 2016-11-24 2200-01-01  lof
501026.XSHG           财通福享    CTFX 2016-12-15 2200-01-01  lof
501027.XSHG           国泰融信    GTRX 2017-06-01 2200-01-01  lof
501028.XSHG           财通福瑞    CTFR 2017-02-20 2200-01-01  lof
501029.XSHG           红利基金    HLJJ 2017-02-13 2200-01-01  lof
501030.XSHG           环境治理    HJZL 2017-02-20 2200-01-01  lof
501031.XSHG            环境C     HJC 2017-02-20 2200-01-01  lof
501032.XSHG           福盛定增    CTFS 2017-04-21 2200-01-01  lof
501035.XSHG           创金睿选    CJRX 2017-09-18 2019-06-06  lof
501036.XSHG         中证500A  ZZ500A 2017-10-09 2200-01-01  lof
501037.XSHG         中证500C  ZZ500C 2017-10-09 2200-01-01  lof
501038.XSHG           银华明择    YHMZ 2017-11-24 2200-01-01  lof
501040.XSHG           添富睿C    TFRC 2018-01-12 2200-01-01  lof
501043.XSHG         沪深300A  HS300A 2017-10-09 2200-01-01  lof
501045.XSHG         沪深300C  HS300C 2017-10-09 2200-01-01  lof
501046.XSHG           财通福鑫    CTFX 2017-12-01 2200-01-01  lof
501047.XSHG           全指证券    QZZQ 2018-01-18 2200-01-01  lof
501048.XSHG            证券C     ZQC 2018-01-18 2200-01-01  lof
501050.XSHG           50AH    50AH 2016-11-28 2200-01-01  lof
501051.XSHG           圆信汇利    YXHL 2018-01-31 2200-01-01  lof
501057.XSHG           新能源车    XNYC 2018-06-20 2200-01-01  lof
501058.XSHG           新能车C    XNCC 2018-06-20 2200-01-01  lof
501059.XSHG           国企红利    GQHL 2018-07-26 2200-01-01  lof
501060.XSHG         金选300A  JX300A 2018-09-25 2200-01-01  lof
501061.XSHG         金选300C  JX300C 2018-09-25 2200-01-01  lof
501062.XSHG           南方瑞合    NFRH 2018-12-05 2200-01-01  lof
501065.XSHG           经典成长    JDCZ 2019-05-08 2200-01-01  lof
501067.XSHG         富时AH50  FSAH50 2019-01-04 2200-01-01  lof
501068.XSHG          AH50C   AH50C 2019-01-04 2200-01-01  lof
501069.XSHG           质量基金    ZLJJ 2019-03-05 2200-01-01  lof
501072.XSHG           红利增强    HLZQ 2019-07-02 2200-01-01  lof
501106.XSHG           十年国开    SNGK 2017-12-13 2200-01-01  lof
501186.XSHG           华夏配售    HXPS 2019-03-29 2200-01-01  lof
501188.XSHG           添富配售    TFPS 2019-03-29 2200-01-01  lof
501189.XSHG           嘉实配售    JSPS 2019-03-29 2200-01-01  lof
501300.XSHG            美元债     MYZ 2017-02-16 2200-01-01  lof
501301.XSHG           香港大盘    XGDP 2017-05-08 2200-01-01  lof
501302.XSHG           恒生联接    HSLJ 2017-08-15 2200-01-01  lof
501303.XSHG           恒生中型    HSZX 2017-10-25 2200-01-01  lof
501305.XSHG           港股高息    GGGX 2018-01-18 2200-01-01  lof
501306.XSHG           港股高C    GGGC 2018-01-18 2200-01-01  lof
501307.XSHG           银河高股    YHGG 2018-04-25 2200-01-01  lof
501309.XSHG            港股通     GGT 2018-12-10 2200-01-01  lof
501310.XSHG           价值基金    JZJJ 2018-11-22 2200-01-01  lof
501311.XSHG          新经济HK   XJJHK 2019-02-14 2200-01-01  lof
502000.XSHG          500等权   500DQ 2015-04-27 2200-01-01  lof
502003.XSHG           军工分级    JGFJ 2015-07-15 2200-01-01  lof
502006.XSHG           国企改革    GQGG 2015-06-25 2200-01-01  lof

### 分级基金列表

In [20]:
get_all_securities(['fja','fjb'],date=None)

            display_name    name start_date   end_date type
150008.XSHE         瑞和小康    RHXK 2009-11-19 2200-01-01  fja
150009.XSHE         瑞和远见    RHYJ 2009-11-19 2200-01-01  fjb
150012.XSHE       中证100A  ZZ100A 2010-06-18 2200-01-01  fja
150013.XSHE       中证100B  ZZ100B 2010-06-18 2200-01-01  fjb
150016.XSHE          合润A     HRA 2010-05-31 2200-01-01  fja
150017.XSHE          合润B     HRB 2010-05-31 2200-01-01  fjb
150018.XSHE         银华稳进    YHWJ 2010-06-07 2200-01-01  fja
150019.XSHE         银华锐进    YHRJ 2010-06-07 2200-01-01  fjb
150022.XSHE         深成指A    SCZA 2010-11-08 2200-01-01  fja
150023.XSHE         深成指B    SCZB 2010-11-08 2200-01-01  fjb
150028.XSHE       中证500A  ZZ500A 2011-03-14 2200-01-01  fja
150029.XSHE       中证500B  ZZ500B 2011-03-14 2200-01-01  fjb
150030.XSHE        中证90A   ZZ90A 2011-04-08 2200-01-01  fja
150031.XSHE        中证90B   ZZ90B 2011-04-08 2200-01-01  fjb
150032.XSHE         多利优先    DLYX 2011-05-06 2200-01-01  fja
150033.XSHE         多利进取    DLJQ 2011-05-06 2200-01-01  fjb
150034.XSHE          聚利A     JLA 2011-07-08 2016-05-12  fja
150035.XSHE          聚利B     JLB 2011-07-08 2016-05-12  fjb
150036.XSHE         建信稳健    JXWJ 2011-06-08 2200-01-01  fja
150037.XSHE         建信进取    JXJQ 2011-06-08 2200-01-01  fjb
150039.XSHE          鼎利A     DLA 2011-09-15 2017-09-14  fja
150040.XSHE          鼎利B     DLB 2011-09-15 2017-09-14  fjb
150047.XSHE          消费A     XFA 2011-10-21 2200-01-01  fja
150048.XSHE          消费B     XFB 2011-10-21 2200-01-01  fjb
150049.XSHE         消费收益    XFSY 2012-04-25 2200-01-01  fja
150050.XSHE         消费进取    XFJQ 2012-04-25 2200-01-01  fjb
150051.XSHE       沪深300A  HS300A 2012-02-17 2200-01-01  fja
150052.XSHE       沪深300B  HS300B 2012-02-17 2200-01-01  fjb
150053.XSHE       泰达500A  TD500A 2011-12-22 2200-01-01  fja
150054.XSHE       泰达500B  TD500B 2011-12-22 2200-01-01  fjb
150055.XSHE         500A    500A 2012-03-30 2200-01-01  fja
150056.XSHE         500B    500B 2012-03-30 2200-01-01  fjb
150057.XSHE       中小300A  ZX300A 2012-02-21 2018-08-03  fja
150058.XSHE       中小300B  ZX300B 2012-02-21 2018-08-03  fjb
150059.XSHE         资源A级    ZYAJ 2011-12-21 2200-01-01  fja
150060.XSHE         资源B级    ZYBJ 2011-12-21 2200-01-01  fjb
150064.XSHE          同瑞A     TRA 2012-01-12 2200-01-01  fja
150065.XSHE          同瑞B     TRB 2012-01-12 2200-01-01  fjb
150066.XSHE          互利A     HLA 2012-01-17 2200-01-01  fja
150067.XSHE          互利B     HLB 2012-01-17 2200-01-01  fjb
150073.XSHE         诺安稳健    NAWJ 2012-04-27 2019-05-28  fja
150075.XSHE         诺安进取    NAJQ 2012-04-27 2019-05-28  fjb
150076.XSHE         浙商稳健    ZSWJ 2012-07-13 2018-08-10  fja
150077.XSHE         浙商进取    ZSJQ 2012-07-13 2018-08-10  fjb
150083.XSHE       深证100A  SZ100A 2012-06-12 2200-01-01  fja
150084.XSHE       深证100B  SZ100B 2012-06-12 2200-01-01  fjb
150085.XSHE         中小板A    ZXBA 2012-05-28 2017-05-05  fja
150086.XSHE         中小板B    ZXBB 2012-05-28 2017-05-05  fjb
150088.XSHE       金鹰500A  JY500A 2012-07-03 2016-08-23  fja
150089.XSHE       金鹰500B  JY500B 2012-07-03 2016-08-23  fjb
150090.XSHE          成长A     CZA 2012-10-12 2018-08-13  fja
150091.XSHE          成长B     CZB 2012-10-12 2018-08-13  fjb
150092.XSHE       诺德300A  ND300A 2012-09-24 2200-01-01  fja
150093.XSHE       诺德300B  ND300B 2012-09-24 2200-01-01  fjb
150094.XSHE       泰信400A  TX400A 2012-09-21 2200-01-01  fja
150095.XSHE       泰信400B  TX400B 2012-09-21 2200-01-01  fjb
150096.XSHE          商品A     SPA 2012-07-25 2017-06-28  fja
150097.XSHE          商品B     SPB 2012-07-25 2017-06-28  fjb
150100.XSHE          资源A     ZYA 2012-10-18 2200-01-01  fja
150101.XSHE          资源B     ZYB 2012-10-18 2200-01-01  fjb
150104.XSHE       HS300A  HS300A 2012-07-23 2200-01-01  fja
150105.XSHE       HS300B  HS300B 2012-07-23 2200-01-01  fjb
150106.XSHE          中小A     ZXA 2012-10-25 2200-01-01  fja
150107.XSHE          中小B     ZXB 2012-10-25 2200-01-01  fjb
150108.XSHE       同辉100A  TH100A 2012-09-26 2017-09-12  fja
150109.XSHE       同辉100B  TH100B 2012-09-26 2017-09-12  fjb
150112.XSHE        深100A   S100A 2012-11-05 2018-04-13  fja
150113.XSHE        深100B   S100B 2012-11-05 2018-04-13  fjb
150117.XSHE         房地产A    FDCA 2013-03-07 2200-01-01  fja
150118.XSHE         房地产B    FDCB 2013-03-07 2200-01-01  fjb
150121.XSHE         银河优先    YHYX 2013-06-06 2018-08-30  fja
150122.XSHE         银河进取    YHJQ 2013-06-06 2018-08-30  fjb
150123.XSHE        建信50A   JX50A 2013-05-20 2200-01-01  fja
150124.XSHE        建信50B   JX50B 2013-05-20 2200-01-01  fjb
150130.XSHE          医药A     YYA 2013-09-11 2200-01-01  fja
150131.XSHE          医药B     YYB 2013-09-11 2200-01-01  fjb
150133.XSHE          德信A     DXA 2013-06-03 2017-04-19  fja
150134.XSHE          德信B     DXB 2013-06-03 2017-04-19  fjb
150135.XSHE       国富100A  GF100A 2015-04-10 2200-01-01  fja
150136.XSHE       国富100B  GF100B 2015-04-10 2200-01-01  fjb
150138.XSHE       中证800A  ZZ800A 2013-12-11 2019-04-15  fja
150139.XSHE       中证800B  ZZ800B 2013-12-11 2019-04-15  fjb
150140.XSHE       国金300A  GJ300A 2013-08-23 2017-08-30  fja
150141.XSHE       国金300B  GJ300B 2013-08-23 2017-08-30  fjb
150143.XSHE         转债A级    ZZAJ 2013-08-28 2200-01-01  fja
150144.XSHE         转债B级    ZZBJ 2013-08-28 2200-01-01  fjb
150145.XSHE         高贝塔A    GBTA 2013-09-02 2200-01-01  fja
150146.XSHE         高贝塔B    GBTB 2013-09-02 2200-01-01  fjb
150148.XSHE       医药800A  YY800A 2013-09-06 2200-01-01  fja
150149.XSHE       医药800B  YY800B 2013-09-06 2200-01-01  fjb
150150.XSHE       有色800A  YS800A 2013-09-18 2200-01-01  fja
150151.XSHE       有色800B  YS800B 2013-09-18 2200-01-01  fjb
150152.XSHE         创业板A    CYBA 2013-09-30 2200-01-01  fja
150153.XSHE         创业板B    CYBB 2013-09-30 2200-01-01  fjb
150157.XSHE          金融A     JRA 2014-01-22 2200-01-01  fja
150158.XSHE          金融B     JRB 2014-01-22 2200-01-01  fjb
150164.XSHE         可转债A    KZZA 2014-06-06 2200-01-01  fja
150165.XSHE         可转债B    KZZB 2014-06-06 2200-01-01  fjb
150167.XSHE       银华300A  YH300A 2014-01-21 2200-01-01  fja
150168.XSHE       银华300B  YH300B 2014-01-21 2200-01-01  fjb
150169.XSHE          恒生A     HSA 2014-04-11 2200-01-01  fja
150170.XSHE          恒生B     HSB 2014-04-11 2200-01-01  fjb
150171.XSHE          证券A     ZQA 2014-03-31 2200-01-01  fja
150172.XSHE          证券B     ZQB 2014-03-31 2200-01-01  fjb
150173.XSHE       TMT中证A  TMTZZA 2014-12-22 2200-01-01  fja
150174.XSHE       TMT中证B  TMTZZB 2014-12-22 2200-01-01  fjb
150175.XSHE         恒中企A     HGA 2014-05-12 2200-01-01  fja
150176.XSHE         恒中企B     HGB 2014-05-12 2200-01-01  fjb
150177.XSHE          证保A     ZBA 2014-05-19 2200-01-01  fja
150178.XSHE          证保B     ZBB 2014-05-19 2200-01-01  fjb
150179.XSHE          信息A     XXA 2014-05-19 2200-01-01  fja
150180.XSHE          信息B     XXB 2014-05-19 2200-01-01  fjb
150181.XSHE          军工A     JGA 2014-04-23 2200-01-01  fja
150182.XSHE          军工B     JGB 2014-04-23 2200-01-01  fjb
150184.XSHE          环保A     HBA 2014-06-16 2200-01-01  fja
150185.XSHE          环保B     HBB 2014-06-16 2200-01-01  fjb
150186.XSHE         军工A级    JGAJ 2014-08-11 2200-01-01  fja
150187.XSHE         军工B级    JGBJ 2014-08-11 2200-01-01  fjb
150188.XSHE         转债优先    ZZYX 2014-08-25 2200-01-01  fja
150189.XSHE         转债进取    ZZJQ 2014-08-25 2200-01-01  fjb
150190.XSHE       NCF环保A  NCFHBA 2014-10-16 2200-01-01  fja
150191.XSHE       NCF环保B  NCFHBB 2014-10-16 2200-01-01  fjb
150192.XSHE          地产A     DCA 2014-09-23 2200-01-01  fja
150193.XSHE          地产B     DCB 2014-09-23 2200-01-01  fjb
150194.XSHE         互联网A    HLWA 2014-09-22 2200-01-01  fja
150195.XSHE         互联网B    HLWB 2014-09-22 2200-01-01  fjb
150196.XSHE          有色A     YSA 2015-04-15 2200-01-01  fja
150197.XSHE          有色B     YSB 2015-04-15 2200-01-01  fjb
150198.XSHE          食品A     SPA 2014-11-05 2200-01-01  fja
150199.XSHE          食品B     SPB 2014-11-05 2200-01-01  fjb
150200.XSHE          券商A     QSA 2014-11-28 2200-01-01  fja
150201.XSHE          券商B     QSB 2014-11-28 2200-01-01  fjb
150203.XSHE          传媒A     CMA 2014-12-22 2200-01-01  fja
150204.XSHE          传媒B     CMB 2014-12-22 2200-01-01  fjb
150205.XSHE          国防A     GFA 2014-12-05 2200-01-01  fja
150206.XSHE          国防B     GFB 2014-12-05 2200-01-01  fjb
150207.XSHE         地产A端    DCAD 2014-12-12 2200-01-01  fja
150208.XSHE         地产B端    DCBD 2014-12-12 2200-01-01  fjb
150209.XSHE         国企改A    GQGA 2014-12-30 2200-01-01  fja
150210.XSHE         国企改B    GQGB 2014-12-30 2200-01-01  fjb
150211.XSHE         新能车A    XNCA 2015-04-13 2200-01-01  fja
150212.XSHE         新能车B    XNCB 2015-04-13 2200-01-01  fjb
150213.XSHE         成长A级    CZAJ 2015-03-27 2200-01-01  fja
150214.XSHE        *成长B级    CZBJ 2015-03-27 2200-01-01  fjb
150215.XSHE         TMTA    TMTA 2015-04-10 2200-01-01  fja
150216.XSHE         TMTB    TMTB 2015-04-10 2200-01-01  fjb
150217.XSHE         新能源A    XNYA 2015-04-09 2200-01-01  fja
150218.XSHE         新能源B    XNYB 2015-04-09 2200-01-01  fjb
150219.XSHE          健康A     JKA 2015-05-08 2200-01-01  fja
150220.XSHE          健康B     JKB 2015-05-08 2200-01-01  fjb
150221.XSHE         中航军A    ZHJA 2015-04-20 2200-01-01  fja
150222.XSHE         中航军B    ZHJB 2015-04-20 2200-01-01  fjb
150223.XSHE         证券A级    ZQAJ 2015-04-10 2200-01-01  fja
150224.XSHE         证券B级    ZQBJ 2015-04-10 2200-01-01  fjb
150225.XSHE         证保A级    ZBAJ 2015-05-28 2200-01-01  fja
150226.XSHE         证保B级    ZBBJ 2015-05-28 2200-01-01  fjb
150227.XSHE          银行A     YHA 2015-04-28 2200-01-01  fja
150228.XSHE          银行B     YHB 2015-04-28 2200-01-01  fjb
150229.XSHE           酒A      JA 2015-05-11 2200-01-01  fja
150230.XSHE          *酒B      JB 2015-05-11 2200-01-01  fjb
150231.XSHE          电子A     DZA 2015-05-28 2200-01-01  fja
150232.XSHE          电子B     DZB 2015-05-28 2200-01-01  fjb
150233.XSHE         传媒业A    CMYA 2015-06-10 2018-08-21  fja
150234.XSHE         传媒业B    CMYB 2015-06-10 2018-08-21  fjb
150235.XSHE         券商A级    QSAJ 2015-05-15 2200-01-01  fja
150236.XSHE         券商B级    QSBJ 2015-05-15 2200-01-01  fjb
150237.XSHE         环保A级    HBAJ 2015-06-26 2200-01-01  fja
150238.XSHE         环保B级    HBBJ 2015-06-26 2200-01-01  fjb
150241.XSHE         银行A级    YHAJ 2015-05-13 2019-05-09  fja
150242.XSHE         银行B级    YHBJ 2015-05-13 2019-05-09  fjb
150243.XSHE          创业A     CYA 2015-07-06 2200-01-01  fja
150244.XSHE          创业B     CYB 2015-07-06 2200-01-01  fjb
150245.XSHE          互联A     HLA 2015-06-26 2200-01-01  fja
150246.XSHE          互联B     HLB 2015-06-26 2200-01-01  fjb
150247.XSHE         传媒A级    CMAJ 2015-05-29 2200-01-01  fja
150248.XSHE        *传媒B级    CMBJ 2015-05-29 2200-01-01  fjb
150249.XSHE         银行A端    YHAD 2015-05-28 2200-01-01  fja
150250.XSHE         银行B端    YHBD 2015-05-28 2200-01-01  fjb
150251.XSHE          煤炭A     MTA 2015-05-28 2200-01-01  fja
150252.XSHE          煤炭B     MTB 2015-05-28 2200-01-01  fjb
150255.XSHE         银行业A    YHYA 2015-06-11 2200-01-01  fja
150256.XSHE         银行业B    YHYB 2015-06-11 2200-01-01  fjb
150257.XSHE          生物A     SWA 2015-06-11 2200-01-01  fja
150258.XSHE          生物B     SWB 2015-06-11 2200-01-01  fjb
150259.XSHE          重组A     ZZA 2015-06-11 2200-01-01  fja
150260.XSHE          重组B     ZZB 2015-06-11 2200-01-01  fjb
150261.XSHE          医疗A     YLA 2015-06-08 2200-01-01  fja
150262.XSHE          医疗B     YLB 2015-06-08 2200-01-01  fjb
150263.XSHE        1000A   1000A 2015-06-16 2200-01-01  fja
150264.XSHE        1000B   1000B 2015-06-16 2200-01-01  fjb
150265.XSHE          一带A     YDA 2015-05-22 2200-01-01  fja
150266.XSHE          一带B     YDB 2015-05-22 2200-01-01  fjb
150267.XSHE         银行A类    YHAL 2015-06-18 2200-01-01  fja
150268.XSHE         银行B类    YHBL 2015-06-18 2200-01-01  fjb
150269.XSHE          白酒A     BJA 2015-06-05 2200-01-01  fja
150270.XSHE          白酒B     BJB 2015-06-05 2200-01-01  fjb
150271.XSHE         生物药A    SWYA 2015-06-05 2200-01-01  fja
150272.XSHE         生物药B    SWYB 2015-06-05 2200-01-01  fjb
150273.XSHE          带路A     DLA 2015-05-25 2200-01-01  fja
150274.XSHE          带路B     DLB 2015-05-25 2200-01-01  fjb
150275.XSHE         一带一A    YDYA 2015-05-22 2200-01-01  fja
150276.XSHE         一带一B    YDYB 2015-05-22 2200-01-01  fjb
150277.XSHE          高铁A     GTA 2015-06-05 2200-01-01  fja
150278.XSHE          高铁B     GTB 2015-06-05 2200-01-01  fjb
150279.XSHE          新能A     XNA 2015-06-05 2200-01-01  fja
150280.XSHE          新能B     XNB 2015-06-05 2200-01-01  fjb
150281.XSHE         金融地A    JRDA 2015-06-26 2200-01-01  fja
150282.XSHE         金融地B    JRDB 2015-06-26 2200-01-01  fjb
150283.XSHE        SW医药A   SWYYA 2015-07-06 2200-01-01  fja
150284.XSHE        SW医药B   SWYYB 2015-07-06 2200-01-01  fjb
150287.XSHE          钢铁A     GTA 2015-06-29 2200-01-01  fja
150288.XSHE          钢铁B     GTB 2015-06-29 2200-01-01  fjb
150289.XSHE         煤炭A级    MTAJ 2015-07-03 2200-01-01  fja
150290.XSHE         煤炭B级    MTBJ 2015-07-03 2200-01-01  fjb
150291.XSHE         银行A份    YHAF 2015-06-15 2200-01-01  fja
150292.XSHE         银行B份    YHBF 2015-06-15 2200-01-01  fjb
150293.XSHE         高铁A级    GTAJ 2015-06-23 2200-01-01  fja
150294.XSHE         高铁B级    GTBJ 2015-06-23 2200-01-01  fjb
150295.XSHE          改革A     GGA 2015-06-15 2200-01-01  fja
150296.XSHE          改革B     GGB 2015-06-15 2200-01-01  fjb
150297.XSHE         互联A级    HLAJ 2015-07-13 2200-01-01  fja
150298.XSHE         互联B级    HLBJ 2015-07-13 2200-01-01  fjb
150299.XSHE         银行股A    YHGA 2015-06-18 2200-01-01  fja
150300.XSHE         银行股B    YHGB 2015-06-18 2200-01-01  fjb
150301.XSHE         证券股A    ZQGA 2015-06-18 2200-01-01  fja
150302.XSHE         证券股B    ZQGB 2015-06-18 2200-01-01  fjb
150303.XSHE         创业股A    CYGA 2015-07-15 2200-01-01  fja
150304.XSHE         创业股B    CYGB 2015-07-15 2200-01-01  fjb
150305.XSHE          养老A     YLA 2015-07-10 2019-03-28  fja
150306.XSHE          养老B     YLB 2015-07-10 2019-03-28  fjb
150307.XSHE          体育A     TYA 2015-07-06 2200-01-01  fja
150308.XSHE          体育B     TYB 2015-07-06 2200-01-01  fjb
150309.XSHE         信息安A    XXAA 2015-07-15 2200-01-01  fja
150310.XSHE         信息安B    XXAB 2015-07-15 2200-01-01  fjb
150311.XSHE          智能A     ZNA 2015-07-15 2200-01-01  fja
150312.XSHE          智能B     ZNB 2015-07-15 2200-01-01  fjb
150315.XSHE         工业4A    GY4A 2015-06-25 2200-01-01  fja
150316.XSHE         工业4B    GY4B 2015-06-25 2200-01-01  fjb
150317.XSHE         E金融A    EJRA 2015-07-08 2200-01-01  fja
150318.XSHE        *E金融B    EJRB 2015-07-08 2200-01-01  fjb
150321.XSHE         煤炭A基    MTAJ 2015-06-30 2200-01-01  fja
150322.XSHE         煤炭B基    MTBJ 2015-06-30 2200-01-01  fjb
150323.XSHE         环保A端    HBAD 2015-07-27 2200-01-01  fja
150324.XSHE         环保B端    HBBD 2015-07-27 2200-01-01  fjb
150325.XSHE         高铁A端    GTAD 2015-08-05 2200-01-01  fja
150326.XSHE         高铁B端    GTBD 2015-08-05 2200-01-01  fjb
150327.XSHE         新能A级    XNAJ 2015-08-03 2200-01-01  fja
150328.XSHE         新能B级    XNBJ 2015-08-03 2200-01-01  fjb
150329.XSHE          保险A     BXA 2015-08-11 2200-01-01  fja
150330.XSHE          保险B     BXB 2015-08-11 2200-01-01  fjb
150331.XSHE         网金融A    WJRA 2015-08-10 2018-08-06  fja
150332.XSHE         网金融B    WJRB 2015-08-10 2018-08-06  fjb
150335.XSHE         军工股A    JGGA 2015-07-13 2200-01-01  fja
150336.XSHE         军工股B    JGGB 2015-07-13 2200-01-01  fjb
150343.XSHE         证券A基    ZQAJ 2015-08-03 2200-01-01  fja
150344.XSHE         证券B基    ZQBJ 2015-08-03 2200-01-01  fjb
502001.XSHG       500等权A  500DQA 2015-04-27 2200-01-01  fja
502002.XSHG       500等权B  500DQB 2015-04-27 2200-01-01  fjb
502004.XSHG          军工A     JGA 2015-07-15 2200-01-01  fja
502005.XSHG          军工B     JGB 2015-07-15 2200-01-01  fjb
502007.XSHG         国企改A    GQGA 2015-06-25 2200-01-01  fja
502008.XSHG         国企改B    GQGB 2015-06-25 2200-01-01  fjb
502011.XSHG          证券A     ZQA 2015-07-15 2200-01-01  fja
502012.XSHG          证券B     ZQB 2015-07-15 2200-01-01  fjb
502014.XSHG         一带一A    YDYA 2015-06-09 2200-01-01  fja
502015.XSHG         一带一B    YDYB 2015-06-09 2200-01-01  fjb
502017.XSHG          带路A     DLA 2015-08-24 2018-10-25  fja
502018.XSHG          带路B     DLB 2015-08-24 2018-10-25  fjb
502021.XSHG        国金50A   GJ50A 2015-06-05 2200-01-01  fja
502022.XSHG        国金50B   GJ50B 2015-06-05 2200-01-01  fjb
502024.XSHG          钢铁A     GTA 2015-08-24 2200-01-01  fja
502025.XSHG          钢铁B     GTB 2015-08-24 2200-01-01  fjb
502027.XSHG         新丝路A    XSLA 2015-08-24 2018-05-14  fja
502028.XSHG         新丝路B    XSLB 2015-08-24 2018-05-14  fjb
502031.XSHG          高铁A     GTA 2015-08-07 2019-02-21  fja
502032.XSHG          高铁B     GTB 2015-08-07 2019-02-21  fjb
502037.XSHG          网金A     WJA 2015-07-07 2200-01-01  fja
502038.XSHG          网金B     WJB 2015-07-07 2200-01-01  fjb
502041.XSHG         上50A    S50A 2015-08-24 2200-01-01  fja
502042.XSHG         上50B    S50B 2015-08-24 2200-01-01  fjb
502049.XSHG        上证50A   SZ50A 2015-04-27 2200-01-01  fja
502050.XSHG        上证50B   SZ50B 2015-04-27 2200-01-01  fjb
502054.XSHG          券商A     QSA 2015-08-24 2200-01-01  fja
502055.XSHG          券商B     QSB 2015-08-24 2200-01-01  fjb
502057.XSHG          医疗A     YLA 2015-07-31 2200-01-01  fja
502058.XSHG          医疗B     YLB 2015-07-31 2200-01-01  fjb

### 货币基金列表

| 货币基金代码 | 货币基金名称 | 起始日期   | 是否T+0 |
| ------------ | ------------ | ---------- | ------- |
| 159001.XSHE  | 保证金       | 2014-10-20 | 是      |
| 159003.XSHE  | 招商快线     | 2014-10-20 | 是      |
| 159005.XSHE  | 添富快钱     | 2015-01-13 | 是      |
| 511600.XSHG  | 货币ETF      | 2016-09-27 | 是      |
| 511620.XSHG  | 货币基金     | 2017-09-07 | 是      |
| 511650.XSHG  | 华夏快线     | 2017-01-16 | 是      |
| 511660.XSHG  | 建信添益     | 2016-09-21 | 是      |
| 511680.XSHG  | 安信货币     | 2016-09-27 | 是      |
| 511690.XSHG  | 交易货币     | 2016-10-20 | 是      |
| 511700.XSHG  | 场内货币     | 2016-10-17 | 是      |
| 511760.XSHG  | 德邦货币     | 2016-12-15 | 是      |
| 511770.XSHG  | 金鹰增益     | 2017-04-10 | 是      |
| 511800.XSHG  | 易货币       | 2014-12-08 | 是      |
| 511810.XSHG  | 理财金H      | 2015-01-05 | 是      |
| 511820.XSHG  | 鹏华添利     | 2016-02-22 | 是      |
| 511830.XSHG  | 华泰货币     | 2015-08-03 | 是      |
| 511850.XSHG  | 财富宝E      | 2016-07-18 | 是      |
| 511860.XSHG  | 博时货币     | 2014-12-09 | 是      |
| 511880.XSHG  | 银华日利     | 2013-04-18 | 是      |
| 511890.XSHG  | 景顺货币     | 2015-08-03 | 是      |
| 511900.XSHG  | 富国货币     | 2015-12-09 | 是      |
| 511910.XSHG  | 融通货币     | 2016-07-04 | 是      |
| 511920.XSHG  | 广发货币     | 2016-03-28 | 是      |
| 511930.XSHG  | 中融日盈     | 2015-12-15 | 是      |
| 511950.XSHG  | 广发添利     | 2016-12-19 | 是      |
| 511960.XSHG  | 嘉实快线     | 2016-01-11 | 是      |
| 511970.XSHG  | 国寿货币     | 2016-07-18 | 是      |
| 511980.XSHG  | 现金添富     | 2015-11-02 | 是      |
| 511990.XSHG  | 华宝添益     | 2013-01-28 | 是      |